version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket sam-lambda-hello-word --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml